// app/layout.tsx
'use client'; 

import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { usePathname } from 'next/navigation'; 
import LandingPage from './landing';

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); 
  const isLandingPage = pathname === '/';

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {isLandingPage ? <LandingPage /> : children}
        </body>
      </html>
    </ClerkProvider>
  );
}


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs"


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//     </ClerkProvider>
//   );
// }
